language: go
go: 1.3
#addons:
#  postgresql: "9.3"
before_script:
  - mysql -uroot -e "CREATE USER 'gomigrate'@'localhost' IDENTIFIED BY 'password';"
  - mysql -uroot -e "GRANT ALL PRIVILEGES ON * . * TO 'gomigrate'@'localhost';"
  - mysql -uroot -e "CREATE DATABASE gomigrate;"
  - go get github.com/go-sql-driver/mysql
script:
  - DB=mysql go test
